// Generated by CoffeeScript 1.3.1
(function() {

  module.exports.chain = function(object, process, fn) {
    var exec, key, keys, value;
    if (object == null) {
      return fn(null);
    }
    keys = (function() {
      var _results;
      _results = [];
      for (key in object) {
        value = object[key];
        _results.push(key);
      }
      return _results;
    })();
    exec = function() {
      if (!(keys.length > 0)) {
        return fn(null);
      }
      key = keys.pop();
      return process(object[key], key, function(err) {
        if (err != null) {
          return fn(err);
        }
        return exec();
      });
    };
    return exec();
  };

}).call(this);
